import type { Teacher } from "./types";

export const teachers: Teacher[] = [
  {
    id: "1",
    name: "Margit Saar-Sibul",
    role: "kutseõpetaja",
    address: "Kopli 1A, Tartu linn",
    room: "A420",
    unit: "IT Akadeemia",
    email: "margit.saar-sibul@voco.ee",
    phone: "",
    image: "https://siseveeb.voco.ee/veebilehe_andmed/pilt?cs=3722&isik=JIrd0bJJJJJJJJJ",
    avgRating: 4.5,
    updatedAt: "2025-12-08T10:00:00.000Z",
    reviews: [],
  },
  {
    id: "2",
    name: "Priit Põld",
    role: "erialaõpetaja",
    address: "Kopli 1, Tartu linn",
    room: "B312",
    unit: "Multimeedia osakond",
    email: "priit.pold@voco.ee",
    phone: "+3725123344",
    image: "https://siseveeb.voco.ee/veebilehe_andmed/pilt?cs=2754&isik=JbzF0YJJJJJJJJJ",
    avgRating: 4.2,
    updatedAt: "2025-12-08T10:05:00.000Z",
    reviews: [],
  },
  {
    id: "3",
    name: "Katrin Vaher",
    role: "õpetaja",
    address: "Tähe 4, Tartu linn",
    room: "C205",
    unit: "Teenindusõppe osakond",
    email: "katrin.vaher@voco.ee",
    phone: "+37255518899",
    image: "https://example.com/img/katrin.jpg",
    avgRating: 4.8,
    updatedAt: "2025-12-08T10:10:00.000Z",
    reviews: [],
  },
  {
    id: "4",
    name: "Madis Tamm",
    role: "kutseõpetaja",
    address: "Narva mnt 22, Tartu linn",
    room: "A101",
    unit: "IT Akadeemia",
    email: "madis.tamm@voco.ee",
    phone: "+3725127788",
    image: "https://example.com/img/madis.jpg",
    avgRating: 4.1,
    updatedAt: "2025-12-08T10:15:00.000Z",
    reviews: [],
  },
  {
    id: "5",
    name: "Liis Karilaid",
    role: "õpetaja",
    address: "Kopli 1A, Tartu linn",
    room: "A302",
    unit: "IT Akadeemia",
    email: "liis.karilaid@voco.ee",
    phone: "5512427",
    image: "https://siseveeb.voco.ee/veebilehe_andmed/pilt?cs=0303&isik=JfbdddJJJJJJJJJ",
    avgRating: 4.7,
    updatedAt: "2025-12-08T10:20:00.000Z",
    reviews: [],
  },
  {
    id: "6",
    name: "Eve Mäeorg",
    role: "kutseõpetaja",
    address: "Kopli 1A, Tartu linn",
    room: "A414",
    unit: "IT Akadeemia",
    email: "eve.maeorg@voco.ee",
    phone: "",
    image: "https://siseveeb.voco.ee/veebilehe_andmed/pilt?cs=5922&isik=JzFbJJJJJJJJJJJ",
    avgRating: 4.3,
    updatedAt: "2025-12-08T10:25:00.000Z",
    reviews: [],
  },
  {
    id: "7",
    name: "Risto Korb",
    role: "õpetaja",
    address: "Kopli 1A, Tartu linn",
    room: "A410",
    unit: "IT Akadeemia",
    email: "risto.korb@voco.ee",
    phone: "+37256216266",
    image: "https://siseveeb.voco.ee/veebilehe_andmed/pilt?cs=1927&isik=JfIrrzJJJJJJJJJ",
    avgRating: 4.6,
    updatedAt: "2025-12-08T10:30:00.000Z",
    reviews: [],
  },
  {
    id: "8",
    name: "Sandra Remmelgas",
    role: "mentor - praktika koordinaator",
    address: "Kopli 1A, Tartu linn",
    room: "A412",
    unit: "IT Akadeemia",
    email: "sandra.remmelgas@voco.ee",
    phone: "56969568",
    image: "https://example.com/img/sandra.jpg",
    avgRating: 4.4,
    updatedAt: "2025-12-08T10:35:00.000Z",
    reviews: [],
  }
];
